<div id="lightBox" class="hidden"></div>
		 
		 <div id="positionBigImage">
			
			 <div id="boundaryBigImage" class="hidden">
				
				<a href="javascript:displayLightBox(-1)"> 
					<img id="x" src="x.png" alt="close">
				</a>
				
				<img id="bigImage" src="x.png" alt="x">
				
				<a href="javascript:imageSelect('left')"><img class="arrows" id="leftArrow" src="leftArrow.png" alt="leftArrow"></a>
				<a href="javascript:imageSelect('right')"><img class="arrows" id="rightArrow" src="rightArrow.png" alt="rightArrow"></a>
			 
				
			 </div> <!-- boundaryBigImage -->
			 
			<div id="imageInfo">
				<p id="name"></p>
				<p id="description"></p>
				<p id="tags"></p>
			</div>
			
		 </div> <!-- positionBigImage -->

</div>
       

</div>