 <h1>Approval Gallery</h1>

<div class="uploader">
	<div class="container">
		
		<a href="index.php?page=logout"><button class="albumButton" onclick="log('out')" type="button">Logout</button></a>
		<a href="index.php"><button class="albumButton" onclick="log('in')" type="button">Back to Gallery</button></a> <br>
		<p class="approvalMessage">Click on an image to approve it</p>

	</div>
	<div class="thumbnailBox">
